### ISSUE TITLE
snuba silently stops processing new events

### ISSUE THREAD

**Issue by drook** [getsentry/snuba#1022]
Versions:
Python 2.7.18
snuba, version 0.0.0, built from git, last commit in the master branch:

````
commit 048d7cf1cc0df866830194f76d5ec46a2dd1f51c (HEAD -> master, origin/master, origin/HEAD)
Author: Filippo Pacifici <filippo.pacifici@gmail.com>
Date:   Thu Jun 11 11:38:30 2020 -0700
````

Snuba silently stops processing new events. This is really everything I can say: it still shows new HTTP 
activity in its log, but new events aren't appearing in the Sentry.

Snuba is running with SNUBA_LOG_LEVEL="WARNING".

Workaround: service restart each 6 hours.

**Comment by fpacifici** [comment]
Hi,
a couple of questions. `Python 2.7.18` I assume this is the python version you are running sentry on, since Snuba runs on 3.7. Is that correct?

> new HTTP activity in its log, but new events aren't appearing in the Sentry.

How are you running snuba? Is it from source or through https://github.com/getsentry/onpremise ?
I think the best option to troubleshoot this is to see the logs of the Kafka consumers, at INFO level. That way we can say whether snuba is receiving events to begin with. Though I need to know how you are running snuba to instruct on how to retrieve the logs.
