### ISSUE TITLE
Consumer Decode Error: The surrogate pair in string is invalid.

### ISSUE THREAD

**Issue by DandyDeveloper** [getsentry/snuba#1085]
Snuba Consumer on startup appears to be reading Kafka and struggling to parse the offset response with the following error:

```2020-07-02 01:36:34,704 New partitions assigned: {Partition(topic=Topic(name='events'), index=0): 3875707}
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 11, in <module>
    load_entry_point('snuba', 'console_scripts', 'snuba')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 162, in consumer
    consumer.run()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 137, in run
    self._run_once()
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 152, in _run_once
    self._handle_message(msg)
  File "/usr/src/snuba/snuba/utils/streams/batching.py", line 177, in _handle_message
    result = self.worker.process_message(msg)
  File "/usr/src/snuba/snuba/consumer.py", line 60, in process_message
    value = rapidjson.loads(message.payload.value)
rapidjson.JSONDecodeError: Parse error at offset 35912: The surrogate pair in string is invalid.
```

I've tried adjusting the `auto-reset-offset` to earliest to change position but it hasn't worked. Looking into other options, but just raising this as a bug

**Comment by tkaemming** [comment]
The `--auto-offset-reset` option is only used if the consumer hasn't already committed an offset, so if the consumer has already done a meaningful amount of work, that option is likely not going to have any effect. I'd also think that you'd also want to set the offset to the _latest_ offset rather than the _earliest_ to skip whatever message(s) are causing problems if that wasn't the case.

Assuming that the consumer didn't just immediately fall over the first time you started it, you have two options here that I'm aware of:

1. If you're running the latest tagged version and not the `master` branch, you should be able to use the `--rapidjson-deserialize false` option.
2. Use the Kafka command line tooling (specifically `kafka-consumer-groups`) to manually advance the offset beyond the offset of the problematic message.

As of #1062 we've moved to rapidjson for all deserialization after using it on sentry.io for some time without issue. If you can share any more details about the specific contents of the message, the consumer (i.e. version you're running, runtime environment, consumer command line flags) and producer (version of Sentry, anything that may be atypical of your installation) that could help replicate the issue, that'd be helpful in case this is an issue that potentially is more widespread than your specific use case.

**Comment by DandyDeveloper** [comment]
@tkaemming Thank you, the `--rapidjson-deserialize false` did the job. 

I'll see if I can dig up the message to get you the content. It was causing the consumer to die every time, so I needed to get a quick fix in but the message should still be there. 

Regarding version: `getsentry/snuba:882be95ba0d462a29759a49b2e9aad0c1ce111a9` is the image I'm using right now. 

Offset is back to latest, I just tried all the available options for the offset to see if I could skip the message in question (Didn't work)
