### ISSUE TITLE
[Question] Snuba upgrade process 

### ISSUE THREAD

**Issue by chhetripradeep** [getsentry/snuba#1143]
Hi 

I see we are now doing regular releases every month. Since postgresql and clickhouse are the two schema based systems in the whole architecture. I am aware that PostgreSQL schema changes are handled via django migrations which works flawless. I am unsure about how are we manage clickhouse schema changes right now. Whether we need to run snuba migrate command during each version upgrade ? I am worried about messing up my production snuba setup. 

I see most of your configuration code goes to your ops repo which isn't open-sourced and documentation around operations side of snuba isn't much. It will be great to cover these things somewhere.

Thank you in advance.

/cc @lynnagara

**Comment by lynnagara** [comment]
Hi @chhetripradeep 

How are you upgrading Sentry/Snuba right now? Are you using https://github.com/getsentry/onpremise and running the `install.sh` script from that repository? That script should automatically perform the Django and ClickHouse migrations (amongst other things) and should be run after every upgrade. In any case, `snuba migrate` should always be safe to run.

Unfortunately our migration system is quite limited right now and we are in the process of overhauling it. Our goal is to move more of our production configuration into the open source repository.

**Comment by chhetripradeep** [comment]
Hello @lynnagara 

Thank you for the continuous work in making snuba great.

Since we are on k8s, we aren't using that. I will look into the script more and understand how it's working.

Currently, we try to upgrade the staging sentry+snuba setup (which is running same version as production config) and see if we face any issue. For now, i have a init container which runs in every deployment `sentry upgrade --noinput` (does django migrations) but wasn't able to find how to achieve the same on snuba side. 

We have clickhouse setup for snuba little different. We converted all MergeTree tables to ReplicatedMergeTree for data replication.

I have a followup question: how can i find out what clickhouse table schema has changed between two version lets say between 20.6.0 and 20.7.1. 

Thank you for the quick responses and help.

**Comment by lynnagara** [comment]
Hi @chhetripradeep 

Unfortunately there isn't a great way to manage this today. The `snuba migrate` script only creates the non replicated versions of ClickHouse tables. In future, this will change and we'll have a setting that can be passed via configuration to toggle this, but this is still some time off.

For now you would have to manage replicated tables manually and check the migration functions for any changes on each table. For example https://github.com/getsentry/snuba/blob/5041121ddf58ef4fd26905f46dea1f280564fd02/snuba/datasets/storages/events.py#L28-92. I know this is probably going to be a rather painful process for now, sorry about that.

We plan to add a changelog to make sure we call out these types of changes between future releases.

**Comment by chhetripradeep** [comment]
Hey @lynnagara 

Thank you for the continuous help and pointing me to the place to look for migrations. I will keep an eye on that. This is very helpful.

Regards,

**Comment by jdotjdot** [comment]
We tried to upgrade our Sentry Kubernetes installation, knowing that there was built-in migrations for Snuba and Django, and ran into this issue. There wasn't any documentation in the charts repo that the Clickhouse tables don't actually support migration, and we seem not to be able to roll back either.

We're new to the Sentry internals, so we're a bit concerned that we've completely bricked our Sentry installation just by upgrading. Is there any clean way back?  We can't even seem to undo the migration since the Snuba command always says that clustered migrations aren't supported.

**Comment by jdotjdot** [comment]
Snuba refuses to even list the migrations, so it's very hard to tell what's there and what isn't there.

**Comment by jwoglom** [comment]
I ran into an issue running the Helm chart of Sentry in a kubernetes environment with out-of-sync migrations between Snuba nodes, manifesting itself with the following exception:

```snuba.migrations.errors.MigrationInProgress: transactions: 0008_transactions_add_timestamp_index```

I was able to fix this by creating a terminal session inside the sentry-snuba-api pod:
```kubectl exec -i -t deployment/sentry-snuba-api -- sh```

Then checking the state of the migrations after setting the CLICKHOUSE_SINGLE_NODE environment variable:
```
# export CLICKHOUSE_SINGLE_NODE="true"
# snuba migrations list
[...]
transactions
[X]  0001_transactions
[X]  0002_transactions_onpremise_fix_orderby_and_partitionby
[X]  0003_transactions_onpremise_fix_columns
[X]  0004_transactions_add_tags_hash_map
[X]  0005_transactions_add_measurements
[X]  0006_transactions_add_http_fields
[X]  0007_transactions_add_discover_cols
[-]  0008_transactions_add_timestamp_index (IN PROGRESS)
[X]  0009_transactions_fix_title_and_message
[...]
```

I then reverted the most recent transaction on each clickhouse node:
```
for ((i=0;i<3;i++)); do
  export CLICKHOUSE_HOST=sentry-clickhouse-$i.sentry-clickhouse-headless;
  snuba migrations reverse --group transactions --migration-id 0009_transactions_fix_title_and_message --force
  export CLICKHOUSE_HOST=sentry-clickhouse-replica-$i.sentry-clickhouse-replica-headless;
  snuba migrations reverse --group transactions --migration-id 0009_transactions_fix_title_and_message --force
done
```

And then did the same thing with migration id `0008_transactions_add_timestamp_index`, which was the one stuck while marked as "IN PROGRESS". After that, I ran `snuba migrations migrate` on each node:

```

export CLICKHOUSE_SINGLE_NODE="true"
for ((i=0;i<3;i++)); do
  export CLICKHOUSE_HOST=sentry-clickhouse-$i.sentry-clickhouse-headless;
  snuba migrations migrate;
  export CLICKHOUSE_HOST=sentry-clickhouse-replica-$i.sentry-clickhouse-replica-headless;
  snuba migrations migrate;
done
```

This, for me at least, got everything into a workable state.

**Comment by rajeshhsejar444** [comment]
@jwoglom I have tried to run migrate command but failing below error due to inactive replicas in the table.

` snuba migrations migrate
2024-09-20 03:16:55,635 Initializing Snuba...
2024-09-20 03:16:58,170 Snuba initialization took 2.535016664012801s
{"module": "snuba.migrations.connect", "event": "Snuba has only been tested on Clickhouse versions up to 21.8 (sentry-clickhouse:9000 - 21.8.13.6). Higher versions might not be supported.", "severity": "warning", "timestamp": "2024-09-20T03:16:58.181356Z"}
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 87, in migrate
    check_for_inactive_replicas()
  File "/usr/src/snuba/snuba/migrations/connect.py", line 130, in check_for_inactive_replicas
    raise InactiveClickhouseReplica("\n".join(sorted(set(inactive_replica_info))))
snuba.migrations.errors.InactiveClickhouseReplica: Storage discover has inactive replicas for table groupassignee_local with 2 out of 3 replicas active.
Storage discover has inactive replicas for table groupedmessage_local with 2 out of 3 replicas active.
Storage errors has inactive replicas for table groupassignee_local with 2 out of 3 replicas active.
Storage errors has inactive replicas for table groupedmessage_local with 2 out of 3 replicas active.`

Can you please help to fix the inactive replicas ?

**Comment by jwoglom** [comment]
> @jwoglom I have tried to run migrate command but failing below error due to inactive replicas in the table.


Sorry but I don't have a running deployment of Clickhouse/Sentry anymore to help with this

**Comment by gagell** [comment]
> [@jwoglom](https://github.com/jwoglom) I have tried to run migrate command but failing below error due to inactive replicas in the table.
> 
> ` snuba migrations migrate 2024-09-20 03:16:55,635 Initializing Snuba... 2024-09-20 03:16:58,170 Snuba initialization took 2.535016664012801s {"module": "snuba.migrations.connect", "event": "Snuba has only been tested on Clickhouse versions up to 21.8 (sentry-clickhouse:9000 - 21.8.13.6). Higher versions might not be supported.", "severity": "warning", "timestamp": "2024-09-20T03:16:58.181356Z"} Traceback (most recent call last): File "/usr/local/bin/snuba", line 33, in <module> sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')()) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/src/snuba/snuba/cli/migrations.py", line 87, in migrate check_for_inactive_replicas() File "/usr/src/snuba/snuba/migrations/connect.py", line 130, in check_for_inactive_replicas raise InactiveClickhouseReplica("\n".join(sorted(set(inactive_replica_info)))) snuba.migrations.errors.InactiveClickhouseReplica: Storage discover has inactive replicas for table groupassignee_local with 2 out of 3 replicas active. Storage discover has inactive replicas for table groupedmessage_local with 2 out of 3 replicas active. Storage errors has inactive replicas for table groupassignee_local with 2 out of 3 replicas active. Storage errors has inactive replicas for table groupedmessage_local with 2 out of 3 replicas active.`
> 
> Can you please help to fix the inactive replicas ?

@rajeshhsejar444 did you fix this issue? I have the same problem
