### ISSUE TITLE
Snuba consumers stops working when one of the clickhouse replicas is unreachable

### ISSUE THREAD

**Issue by pyhp2017** [getsentry/snuba#6603]
### Environment

I'm Running Sentry 24.9.0 in Kubernetes (self-hosted). I'm using clickhouse with replicas (3 shards and 3 replicas - in total 6 pods).

### Steps to Reproduce

I just removed one of replicas (but the primary still exists). but unfortunately all the Snuba consumers  will go through crash loop backoff and it says this:
snuba.clickhouse.errors.ClickhouseWriterError: DB::Exception: Not found address of host: sentry-clickhouse-replica-2.sentry-clickhouse-replica-headless.sentry.svc.cluster.local: Insert

### Expected Result

If one of the replicas is not accessible it should still work since others exist (that's the whole point of being HA)

### Actual Result

snuba.clickhouse.errors.ClickhouseWriterError: DB::Exception: Not found address of host: sentry-clickhouse-replica-2.sentry-clickhouse-replica-headless.sentry.svc.cluster.local: Insert

**Comment by mcannizz** [comment]
Hi, can you tell us more about how you route `INSERT` queries among the replicas in your ClickHouse cluster? Do you send all `INSERTs` to one server and let ClickHouse replicate them itself, or are you doing something else?

This is the architecture we use internally at Sentry for high availability:
* one set of servers accepts queries and routes them via the `Distributed` table engine
* a separate set of servers actually store data (these have multiple replicas per shard)

This approach has worked well for us and is robust to the failure of any single server.

**Comment by pyhp2017** [comment]
Thank you for your response. After debugging the code, I discovered that the issue was caused by the following configuration:

```python
writer = table_writer.get_batch_writer(
    metrics,
    {"load_balancing": "in_order", "insert_distributed_sync": 1},
    slice_id=slice_id,
)
```
The problem arises because one of the replicas is currently unreachable. Since the `insert_distributed_sync` setting is set to `1`, it forces the operation to verify that the write succeeds on all replicas, leading to failures when any replica is unavailable. Would it be possible to make this setting configurable on the user's side? In our company, this behavior causes significant disruption, as it leads to all Snuba pods crashing under similar conditions. We believe allowing customization of this setting would provide greater flexibility and improve fault tolerance. What are your thoughts?

**Comment by mcannizz** [comment]
Hi, thanks for debugging the problem further. My understanding is that `insert_distributed_snyc = 1` makes `INSERT` queries to the `Distributed` table engine wait until the data is inserted into all the _shards_, not replicas. Presumably if data cannot be inserted into a shard but the insert is allowed to complete, there's a risk of data loss. Is that the behavior you are looking for?

In Sentry's environment, we don't want that behavior and as far as I'm aware we've never had a Snuba consumer crash because a single replica in a shard was offline.

Here are some references I used to learn more about `insert_distributed_sync`:
- https://clickhouse.com/docs/en/whats-new/changelog/2017#clickhouse-release-1-1-54276-2017-08-16
- https://github.com/ClickHouse/ClickHouse/issues/20053#issuecomment-773069116

**Comment by pyhp2017** [comment]
thanks Matt, it seems there was problem with my internal_replication setting. Thanks for your help!
