### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by MaggotMouth** [getsentry/snuba#688]
Any plans on using proper releases for this project?  

Having to run off `latest` and getting unintended upgrades/updates/bugs/incompatibilities with other apps isn't very nice.

Edit:  To clarify, I'm talking about both Github releases and Dockerhub tags

**Comment by BYK** [comment]
I don't think making marked releases is in scope for the near term, if ever as Snuba is a core and evolving part of Sentry which is also on continuous release.

@tkaemming @fpacifici any comments?

**Comment by tkaemming** [comment]
Are you able to elaborate on what you mean by "other apps"?

**Comment by MaggotMouth** [comment]
> Are you able to elaborate on what you mean by "other apps"?

I was referring to Sentry.  I was trying to individually deploy the components to run Sentry 10 in Kubernetes. 

> I don't think making marked releases is in scope for the near term, if ever as Snuba is a core and evolving part of Sentry which is also on continuous release.
> 
> @tkaemming @fpacifici any comments?

If I can install Sentry 10.0.0 somewhere, I'd expect a core component to have related versioning, in case the core component has an incompatible update. What if you make a Snuba release that's only compatible with Sentry 10.5.9 and later, but I'm not ready for that update yet (due to whatever reason)?  Now my Sentry 10.0.0 setup breaks because I have to run off master, or a specific git hash of Snuba.  Continuous release doesn't mean you can't have versioning.

**Comment by BYK** [comment]
>If I can install Sentry 10.0.0 somewhere, I'd expect a core component to have related versioning, in case the core component has an incompatible update. What if you make a Snuba release that's only compatible with Sentry 10.5.9 and later, but I'm not ready for that update yet (due to whatever reason)? Now my Sentry 10.0.0 setup breaks because I have to run off master, or a specific git hash of Snuba.

This is a fair concern and a shortcoming on our side that we're planning to address soon. Our idea for v10 and beyond was to make everyone use the very latest version of all services like we do for SaaS. The key here is, when you use the `:latest` tag for all services at a certain time `t`, they are all guaranteed to be compatible which each other as that's what we are running on sentry.io.

The issue came up when I tagged Sentry v10, just for traditional reasons (if you go and run the install script over at our on-premise repo, it will actually pull in the latest version from master, not the v10 tag), to give people something to hold on. It has nothing extra (well there's a pip package) than any other Docker images we publish. But now it is fixed in time with the expectations and potential breakages to happen in the future.

I think a good solution to this is creating a `10.0.x` branch with fixed service image versions on the onpremise repo and tag that as 10 but keep referring people to master. What do you think @MaggotMouth?


>Continuous release doesn't mean you can't have versioning.

We do have versioning, they are Git SHAs :D Otherwise I disagree with this statement, continuous release means there's only one version: latest.

**Comment by BYK** [comment]
I think we either should move this issue to [getsentry/onpremise](https://github.com/getsentry/onpremise) or create a new one there, referring back to this and close this issue.

**Comment by MaggotMouth** [comment]
> I think a good solution to this is creating a 10.0.x branch with fixed service image versions on the onpremise repo and tag that as 10 but keep referring people to master. What do you think @MaggotMouth?

I'm not sure I'm following you here, can you perhaps provide examples so I'm sure we're on the same page?

If you mean to change (for example) this line https://github.com/getsentry/onpremise/blob/master/docker-compose.yml#L31
to include a specific git sha for Snuba, that would have no bearing on the Dockerhub images.  I'm not using docker compose, I'm only using the available Dockerhub images.

> The key here is, when you use the :latest tag for all services at a certain time t, they are all guaranteed to be compatible which each other as that's what we are running on sentry.io.

The problem with this idea in a Kubernetes world is if I set my containers to pull new images on a restart. 
Imagine I've got 6 instances (for HA/performance/whatever) of each service running in containers (and have been running non-stop for like a month) - all tagged with `latest`. One of the nodes that one of the containers is running on dies, a new node spins up, and the container restarts on the new node.  When the `latest` image pulls (a month newer than the previous `latest` image), it'll now be a different version than the other 5 containers which have been running.  In order to bring everything back into balance, I'd need to restart _every_ container related to Sentry, whenever a single one dies.

**Comment by BYK** [comment]
@MaggotMouth now I realize that we were not publishing per-sha tags to Docker Hub and only had `:latest` there. This should be resolved with #700 and #711 so now we can tag using commit-SHAs and treat them as versions in on-premise.

**Comment by muthusk** [comment]
I am tagging  the current latest version of snuba and symbolicator to my own docker hub repository as v10.0.0 so that I know it is compatible with onpremise Sentry v10.0.0.

**Comment by BYK** [comment]
@muthusk @MaggotMouth we've listened to this feedback and now you can find tagged images for Snuba, Sentry, and Relay, along with the on-premise repo itself.

We have switched to CalVer and the initial release is 20.6.0 (keep an eye on our blog for a more detailed post soon) and I've also retroactively tagged a 10.0.0 version of snuba aligned with the 10.0.0 version of Sentry. This was also applied to on-premise.

Hope this helps you.
