### ISSUE TITLE
Allow configuring sasl arguments for connecting to kafka

### ISSUE THREAD

**Issue by alexef** [getsentry/snuba#974]
Hi there!

Our Kafka cluster requires when bootstrapping connection:
- sasl_mechanism
- sasl_plain_username
- sasl_plain_password

Any chance this can be configured in snuba? I can make a PR if you point me into the right direction.

**Comment by alexef** [comment]
Ping?

**Comment by fpacifici** [comment]
Hi, sorry for the delay.
Unfortunately we do not have any plan right now to expand the way the connection to Kafka can be configured. If you want to give it a try we will be supportive for sure, though, before you get into this, I need to inform you that building the support for such parameters will be a bit involved. Now we have very limited capability for passing parameters to Kafka and some structure will have to be built before adding three of them.

I think you should look into these:
1) does the python confluent api even allow for you to set those parameters: https://docs.confluent.io/current/clients/confluent-kafka-python/#consumer. It should but you may want to double check
2) We keep connection configuration in settings.py so we can change them between environments, this should look the same. See as an example the way we connect to clickhouse: https://github.com/getsentry/snuba/blob/master/snuba/settings.py#L19-L37
3) Unfortunately we did not yet build anything equivalent to Clusters for Kafka as we did for Clickhouse. This should be added to achieve this goal: https://github.com/getsentry/snuba/blob/master/snuba/settings.py#L71-L72
4) We need to support multiple brokers, so these settings cannot be just top level constants in settings.py as we do for the name. That's why this is involved.
5) The parameters need to go all the way from the consumer scripts to the consumer builder: cli/consumer.py -> consumer_builder.py -> streams/kafka.py
6) Also the producer will have to be adapted since Snuba also produces messages to Kafka.

Sorry about this complexity, we just did not get to this yet, if you want to try we will be happy to support you, but as you may see, it is going to take some time.

Filippo

**Comment by alexef** [comment]
Hi @fpacifici, thank you for the details. I will give it a try in the following week.
